---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:dolph/sapper.git
    branch: master
    private_key: {{ssh_private_key}}
- name: weekly
  type: time
  source:
    interval: 168h
- name: image
  type: docker-image
  source:
    repository: dolphm/go-skeleton-test
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}

jobs:
- name: build-image
  serial: true
  build_logs_to_retain: 3
  plan:
  - get: repo
    trigger: false
  - get: weekly
    trigger: true
  - put: image
    attempts: 1
    params:
      build: repo/ci/docker/test
- name: lint
  serial: false
  build_logs_to_retain: 10
  plan:
  - get: image
    trigger: false
    passed: [build-image]
  - get: repo
    trigger: true
  - task: test
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/go-skeleton-test
      inputs:
      - name: repo
      run:
        path: repo/ci/lint.sh
- name: test
  serial: false
  build_logs_to_retain: 10
  plan:
  - get: image
    trigger: false
    passed: [build-image]
  - get: repo
    trigger: true
  - task: test
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: dolphm/go-skeleton-test
      inputs:
      - name: repo
      run:
        path: repo/ci/test.sh
