---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:dolph/sapper.git
    branch: master
    private_key: {{ssh_private_key}}
- name: weekly
  type: time
  source:
    interval: 168h
- name: periodic
  type: time
  source:
    interval: 1h

jobs:
- name: lint
  serial: false
  build_logs_to_retain: 10
  plan:
  - get: repo
    trigger: true
  - task: test
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang:1.9
      inputs:
      - name: repo
      run:
        path: repo/ci/lint.sh
- name: test
  serial: false
  build_logs_to_retain: 10
  plan:
  - get: repo
    trigger: true
  - task: test
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang:1.9
      inputs:
      - name: repo
      run:
        path: repo/ci/test.sh
- name: run
  serial: true
  build_logs_to_retain: 20
  plan:
  - get: repo
    trigger: true
    passed: [test]
  - get: periodic
    trigger: true
  - task: test
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang:1.9
      inputs:
      - name: repo
      run:
        path: repo/ci/run.sh
      params:
        WORDPRESS_ENDPOINT: {{wordpress_endpoint}}
        WORDPRESS_COOKIE: {{wordpress_cookie}}
